export const ageList = [
  { label: '10s', values: '10s' },
  { label: '20s', values: '20s' },
  { label: '30s', values: '30s' },
  { label: '40s', values: '40s' },
  { label: '50s', values: '50s' },
  { label: '60s', values: '60s' },
  { label: '70s +', values: '70s +' },
]
export const industryList = [
  { label: 'Agriculture & Mining', values: 'Agriculture & Mining' },
  { label: 'Construction', values: 'Construction' },
  { label: 'Automotive & Transportation', values: 'Automotive & Transportation' },
  { label: 'Electronics', values: 'Electronics' },
  { label: 'Machinery', values: 'Machinery' },
  { label: 'Materials', values: 'Materials' },
  { label: 'Energy', values: 'Energy' },
  { label: 'Food, Drug, Cosmetics', values: 'Food, Drug, Cosmetics' },
  { label: 'Other Manufacturing', values: 'Other Manufacturing' },
  {
    label: 'Wholesale, Retail & Commerce (incl. Trading Companies)',
    values: 'Wholesale, Retail & Commerce (incl. Trading Companies)',
  },
  { label: 'Finance, Securities, Insurance', values: 'Finance, Securities, Insurance' },
  { label: 'Real Estate', values: 'Real Estate' },
  { label: 'Communication Services', values: 'Communication Services' },
  { label: 'Information Technology, SI, Software', values: 'Information Technology, SI, Software' },
  { label: 'Shipping', values: 'Shipping' },
  { label: 'Consulting, Accounting, Legal', values: 'Consulting, Accounting, Legal' },
  { label: 'Broadcast, Publishing, Advertisement, Media', values: 'Broadcast, Publishing, Advertisement, Media' },
  { label: 'Government Employee (excl. Teachers)', values: 'Government Employee (excl. Teachers)' },
  { label: 'Education & Learning Support', values: 'Education & Learning Support' },
  { label: 'Medical', values: 'Medical' },
  { label: 'Nursing, Caretaking & Welfare', values: 'Nursing, Caretaking & Welfare' },
  { label: 'Restaurant & Hospitality', values: 'Restaurant & Hospitality' },
  { label: 'Personnel Services', values: 'Personnel Services' },
  { label: 'Travel', values: 'Travel' },
  { label: 'Other', values: 'Other' },
]

export const occupationList = [
  { label: 'Corporate Management / Board Member', values: 'Corporate Management / Board Member' },
  { label: 'Business Planning and Development', values: 'Business Planning and Development' },
  { label: 'Public Relations / Promotion', values: 'Public Relations / Promotion' },
  { label: 'General Affairs / HR', values: 'General Affairs / HR' },
  { label: 'Materials / Procurement', values: 'Materials / Procurement' },
  { label: 'Finance & Accounting', values: 'Finance & Accounting' },
  { label: 'General Office', values: 'General Office' },
  { label: 'IT, IT Systems', values: 'IT, IT Systems' },
  { label: 'Planning, Market Study, Marketing', values: 'Planning, Market Study, Marketing' },
  { label: 'Sales', values: 'Sales' },
  { label: 'Production, Manufacturing', values: 'Production, Manufacturing' },
  { label: 'Logistics / Shipping', values: 'Logistics / Shipping' },
  { label: 'Engineering & Design', values: 'Engineering & Design' },
  { label: 'Research & Development', values: 'Research & Development' },
  { label: 'Editing, Compiling, Production', values: 'Editing, Compiling, Production' },
  { label: 'Architecture / Construction', values: 'Architecture / Construction' },
  { label: 'Medical', values: 'Medical' },
  { label: 'Accounting', values: 'Accounting' },
  { label: 'Student', values: 'Student' },
  { label: 'Other', values: 'Other' },
]
